ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "tiempoPrepMin" INTEGER NOT NULL DEFAULT 8;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "esMenuBeca" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "tipo" TEXT NOT NULL DEFAULT 'Normal';
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "tiempoEstimadoMin" INTEGER;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "fechaListo" TIMESTAMP(3);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "fechaEntregado" TIMESTAMP(3);